Progress Bar
ThePyrotechnic/pygrader pull request #37
Opened 2018-03-09 00:07 UTC by egregius313

The current implementation of progress bars is not cross platform.

This set of changes replaces the current implementation of progress
bars with the package `progressbar2` which includes a full
implementation of progress-bars which can be configured if a different
output is desired.

Additionally removed a few `if type(x) == T:` type lines.

2018-03-09 17:20 UTC, ThePyrotechnic requested changes

2018-03-09 17:20 UTC, ThePyrotechnic commented on pycanvasgrader.py
> +    os.system('cls' if os.name == 'nt' else 'clear')
Switch this to use the new function

2018-03-10 20:54 UTC, egregius313 commented on pycanvasgrader.py
> +    os.system('cls' if os.name == 'nt' else 'clear')
I can definitely do that, but this was branched from the original version of master that didn't have the `clear_screen` function. So is it better to do it here without a definition of `clear_screen` or merge this and then change it?

2018-03-10 21:03 UTC, ThePyrotechnic commented on pycanvasgrader.py
> +    os.system('cls' if os.name == 'nt' else 'clear')
Rebase this branch from master, update the line, then push again

2018-03-10 21:13 UTC, egregius313 commented
Fixed the `clear_screen` issue

2018-12-04 17:13 UTC, closed without merging